server:
  port: 8080

level:
  com:
    checkmarx: DEBUG
#            RestTemplate: TRACE

cx-flow:
  bug-tracker: GitHub
  branches:
    - main

checkmarx:
  username: admin@cx
  password: pT62N$@t!J
  base-url: http://localhost
  team: /CxServer
  version: 9.0
  multi-tenant: false


github:
  webhook-token: c57325dc-c7a9-11ed-afa1-0242ac120002
  token: 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
